# =========================
# Informations du site
# =========================

title: "Richard Vin"
description: "Consultant Data"
url: "https://richardvin.github.io"
baseurl: ""

# =========================
# Thème
# =========================

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# =========================
# Paramètres généraux
# =========================

locale: "fr-FR"
search: true

# =========================
# Auteur (colonne gauche)
# =========================

author:
  name     : "Richard Vin"
  avatar   : "/assets/images/RVI portrait.png"
  bio      : "Consultant Data"
  location : "Paris, France"

  github   : "RichardVin"
  linkedin : "https://www.linkedin.com/in/richard-vin-a92018240/"

# =========================
# Pages
# =========================

include:
  - _pages

# =========================
# Plugins (minimum utile)
# =========================

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# =========================
# Defaults
# =========================

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
